---
title: "Main"
format: html
---

```{r}
# Load .CSV and save as .RDS

datacsv <- read.csv("./data/raw/diabetes.csv", header = TRUE)
saveRDS(datacsv, "./data/raw/dataset.rds")

# Preprocessing
dataRDS <- readRDS("./data/raw/dataset.rds")
dataRDS <- na.omit(dataRDS) # removes NA from important columns
saveRDS(dataRDS, "./data/processed/dataset.rds")
dataset <- readRDS("./data/processed/dataset.rds")

# Recoding BMI to classes
dataRDS$BMI[dataRDS$BMI <= 18.5 ] <- 1
dataRDS$BMI[dataRDS$BMI > 18.5 & dataRDS$BMI <= 25  ] <- 2
dataRDS$BMI[dataRDS$BMI > 25 & dataRDS$BMI <= 30 ] <- 3
dataRDS$BMI[dataRDS$BMI > 30] <- 4

summary(dataset)

# cleannames columns for dataset
dataRDS <- clean_names(dataRDS)
```

```{r}
dataRDS
pairs(dataRDS)

model2 <- lm(Outcome ~ Age + BMI, 
             data = dataRDS)

# Ask for summary statistics again
summary(model2)

library(ggplot2)

# Assuming 'df' is your data frame with columns 'y', 'x1', 'x2'

# Plot with regression line for x1
ggplot(dataRDS, aes(x = Age, y = Outcome)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) + # se = FALSE to hide confidence interval
  labs(title = "Relationship between y and x1")

# Plot with regression line for x2
ggplot(dataRDS, aes(x = BMI, y = Outcome)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Relationship between y and x2")


```
